char cmd_chr 64 # default: 64 (@), as this default values is highly unlikely to not be used for anything in deployemnt
float32 arg1 0 # default: 0
float32 arg2 0 # default: 0
float32 arg3 0 # default: 0
float32 arg4 0 # default: 0
float32 arg5 0 # default: 0
float32 arg6 0 # default: 0
float32 arg7 0 # default: 0
float32 arg8 0 # default: 0
float32 arg9 0 # default: 0
float32 arg10 0 # default: 0
float32 arg11 0 # default: 0
float32 arg12 0 # default: 0
float32 arg13 0 # default: 0
float32 arg14 0 # default: 0