char cmd_chr 64 # default: 64 (@), as this default values is highly unlikely to not be used for anything in deployemnt
int32 arg1 0 # default: 0
int32 arg2 0 # default: 0
int32 arg3 0 # default: 0
---
string controller_data "" # default: empty string